### ISSUE TITLE
'princomp' can only be used with more units than variables

### ISSUE THREAD

**Issue by ngroberts** [mongiardino/genesortR#1]
Hello,

I apologize I cannot diagnose this myself as I am not familiar with R, but I keep getting this error and I believe my script is set up correctly.

> Loci with less than 15 taxa will be discarded.
> Error in princomp.default(variables[, variables_to_use], cor = T, scores = T) : 
>   'princomp' can only be used with more units than variables

Best,

**Comment by mongiardino** [comment]
Hi, thanks for sharing this!
`princomp` (the function this script uses for PCA) does not accept matrices where the number of observations (genes in this case) are less than the number of variables (gene properties). So you are either working with a dataset of just a handful of loci, or there is something wrong in the way the loci are being specified. The number of rows of the dataset ultimately is set to the number of trees in the `gene_trees ` object, so if your dataset is bigger then I would check that the correct tree file is being used.
If on the other hand you are trying to use this script with just a few loci, I am sorry but I don't think this is the best approach. PCA can be done with datasets with less observations than variables, and other functions can do so, but the resulting dimensions are poorly constrained and this is generally not advised. I have used _genesortR_ with datasets of ~ 30 loci and it worked well, but I wouldn't recommend going lower than that.
Cheers,
Nico

**Comment by ngroberts** [comment]
Thank you for the info!
This dataset is 25 loci, and I was using this dataset to test genesortR in my pipeline and become familiar with output as I have a larger dataset still in the pipe. I see now why this is a problem as this subset has too few genes for the number of variables.
I will also make sure to double check the number of trees before running in the future.
This is a nice script with great visuals.
Best,
Nick

**Comment by mongiardino** [comment]
Absolutely, thanks for using it!
Like I said, I wouldn't really recommend its use with ~25 loci, but it still shouldn't be failing with that size. I can think of two explanations, either you are using the wrong gene tree file as input, or your dataset is very sparse. There is a threshold to include loci, which is automatically set to 10% of the ingroup (or of the entire dataset if you do not specify an ingroup). So if your data has low occupancy, few of your genes will have more than 10% of ingroup terminals and will be discarded, potentially reducing the number of observations in the dataset.
If neither one of these explanations make sense you are welcome to send me the files by email (matrix, partition, gene trees, species tree) and I will find out what is happening.
Best,
Nico
