### ISSUE TITLE
Clarification of input file format

### ISSUE THREAD

**Issue by THccaa** [mongiardino/genesortR#2]
Hi,
I just came across your paper from last year and I quite like the method because it does not require to determine any thresholds or decide which statistic is more or less important.
I have transcriptome data with ~4500 orthogroups and would like to try your script to increase the signal/noise ratio. However, I do not quite understand the format of the input files. The species tree is clear, but how do the other files suppose to look like?

Is the alignment FASTA a single FASTA file containing all loci? Like this:
>locus-1_species-1
sequence
>locus-1_species-2
sequence
>locus-1_species-3
sequence
>locus-1_species-4
sequence
>locus-2_species-1
sequence
>locus-2_species-2
sequence
>locus-2_species-3
sequence
>locus-2_species-4
sequence
>locus-3_species-1
sequence
>locus-3_species-2
sequence
>locus-3_species-3
sequence
>locus-3_species-4
sequence
...

I guess the partition file should have one locus per line. But what does start/end mean? The lines that belong to the same locus in the FASTA? So in my toy example above:
locus-1 = 1-8
locus-2 = 9-16
locus-3 = 17-24
...

Same with the gene trees: one tree per line and then in the same order as the partition file? Like this:
newick-tree_locus-1
newick-tree_locus-2
newick-tree_locus-3
...

Sorry if this is obvious, but I don't get it.

**Comment by THccaa** [comment]
I figured it out, so I will close this issue with the answer in case someone else has the same problem in the future.

The alignment FASTA is supposed to look like this:

>\>species-1
Sequence-locus1Sequence-locus2Sequence-locus3...
\>species-2
Sequence-locus1Sequence-locus2Sequence-locus3...
\>species-3
Sequence-locus1Sequence-locus2Sequence-locus3...
...

In this example, each sequence (Sequence-locusN) has 15 characters (nucleotides/AAs). So, the partition file for this FASTA would be:
>locus-1 = 1-15
locus-2 = 16-30
locus-3 = 31-45
...

The corresponding gene tree file would be:
>newick-tree_locus-1
newick-tree_locus-2
newick-tree_locus-3

If someone starts from many multiple sequence alignment files, the 'SuperMatrix' function of the R package 'evobiR' comes in handy. It creates the supermatrix FASTA (which can be quickly converted into the correct format in a few steps with bash) and the correct partition file. Just like in the paper, ParGenes (https://github.com/BenoitMorel/ParGenes) can be used to create gene trees. If it is used with '--use-astral' is will create a gene tree file that can be readily inputted into genesortR.

**Comment by theo-allnutt-bioinformatics** [comment]
Thanks for this - I had the same questions. Disappointing that the author did not reply.
