### ISSUE TITLE
enframe() error

### ISSUE THREAD

**Issue by hyyuu** [mongiardino/genesortR#5]
Hello, thank you for this script ! 
I encounter this error when I test genesortr on my data. May I know how to fix this ? Sorry I am not very familiar with R . 
```
> partitions <- read.table(partition, sep = ' ')
> names <- as.character(unlist(enframe(partitions[,(which(partitions[1,] == '=') - 1)], name = NULL), use.names = F))
Error:
! The `x` argument to `enframe()` must be a vector, not data.frame.
```

Thank you again !

Best, 
Alex

**Comment by mongiardino** [comment]
Hi Alex,
Thanks for reaching out.
It looks like read.table() isn't producing the type of output that enframe() requires, which probably means that your partition file is not in the expected format. Please check that you are correctly linking your partition file, and that it is a text file formatted in RAxML style, which should look like this:

gene1 = 1-449
gene2 = 450-1293
...

If you keep encountering this issue after confirming this, please send your partition file by email to me.
Best,
Nico

**Comment by hyyuu** [comment]
Hi Nico, 

I found that all my gene names came with a ".fa" extension, genesortr now run smoothly after I removed the ".fa" .
Thank you so much for your help !

Best, 
Alex
