### ISSUE TITLE
Problem with p-dist

### ISSUE THREAD

**Issue by luishdez35** [mongiardino/genesortR#6]
Hello, thank you for this script, is amazing. 
I am trying to use it but I have a problem in the line 252 with the command:
`p_dist <- as.matrix(dist.hamming(as.phyDat(gene, type = type), ratio = TRUE, exclude = "pairwise"))`

The error is 
```
Error in tabulate(index, max(index)) : invalid value of 'nbins'
In addition: Warning messages:
1: In max(index) : no non-missing arguments to max; returning -Inf
2: In tabulate(index, max(index)) :
  NAs introduced by coercion to integer range
```

Can you please help me? 

Thanks

**Comment by mongiardino** [comment]
Hola Luis!
I am glad the script has been useful for you (and I'm sorry for the late reply).
This error relates to some unexpected structure in your datasets, which I can't really figure out without having them. I would gladly take a look if you can send me an email with all the files you are using to run it.
Cheers,
Nico
