### ISSUE TITLE
Error in princomp.default(variables[, variables_to_use], cor = T, scores = T) :   cannot use 'cor = TRUE' with a constant variable

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [mongiardino/genesortR#7]
Getting this error, unsure why. Thanks.

Loci with less than 25 ingroup will be discarded.
Error in princomp.default(variables[, variables_to_use], cor = T, scores = T) :
  cannot use 'cor = TRUE' with a constant variable
[mo_gcf_scf.cf.tree.txt](https://github.com/mongiardino/genesortR/files/11953744/mo_gcf_scf.cf.tree.txt)

Calls: princomp -> princomp.default
Execution halted
[genetrees.txt](https://github.com/mongiardino/genesortR/files/11953745/genetrees.txt)
[parts.txt](https://github.com/mongiardino/genesortR/files/11953746/parts.txt)
[all-matrix.fasta.txt](https://github.com/mongiardino/genesortR/files/11953748/all-matrix.fasta.txt)

**Comment by theo-allnutt-bioinformatics** [comment]
[genesortR.R.txt](https://github.com/mongiardino/genesortR/files/11953755/genesortR.R.txt)

**Comment by theo-allnutt-bioinformatics** [comment]
This seems to be due to constant values in the matrix - which in alignments there always are.. Do the alignments need to be trimmer to only snps / indels?? That would be very unusual.

**Comment by theo-allnutt-bioinformatics** [comment]
N.B. the tree above was not rooted - I rooted it but got same result.
[rooted.tree.txt](https://github.com/mongiardino/genesortR/files/11953946/rooted.tree.txt)

**Comment by theo-allnutt-bioinformatics** [comment]
ok, this seems to be due to one gene having no variation in alignment.. now removed.

**Comment by theo-allnutt-bioinformatics** [comment]
I started from scratch with new alignments and made sure I removed all Ns and n (to '-'), and the problem didn't occur.

**Comment by theo-allnutt-bioinformatics** [comment]
ok, I have tried everything and still getting this error. all my alignments have variation and still getting this error.

Here are the latest files:
[all-matrix.fasta.txt](https://github.com/mongiardino/genesortR/files/11964974/all-matrix.fasta.txt)

[genesortR.R.txt](https://github.com/mongiardino/genesortR/files/11964977/genesortR.R.txt)

[genetrees.txt](https://github.com/mongiardino/genesortR/files/11964978/genetrees.txt)


[parts.txt](https://github.com/mongiardino/genesortR/files/11964979/parts.txt)

[rooted.tree.txt](https://github.com/mongiardino/genesortR/files/11964980/rooted.tree.txt)

**Comment by theo-allnutt-bioinformatics** [comment]
I see now, it is because my reference tree does not have bootstraps..

**Comment by mongiardino** [comment]
Hi Theo,
It looks like you have figured out all of this on your own.
Regarding your first question, alignments don't need to be edited in any way, and I think (although I am not entirely sure) that the script would run even if an entirely conserved loci is provided. On the second topic you raised, yes, trees with bootstraps are required by the method. That is probably what was causing the error all along, as all genes would get a value of 0 for average bootstrap is the trees provided don't have numbers, and the PCA would fail due to the dataset having a constant variable (as reported in the error message in the first post).
Let me know if you run into any other problems after you get trees with bootstraps.

**Comment by theo-allnutt-bioinformatics** [comment]
My tree has boostrap node labels, but still getting all zeros in the average_BS_support column.

[mo_spp_reroot.tree.txt](https://github.com/mongiardino/genesortR/files/11973719/mo_spp_reroot.tree.txt)

**Comment by theo-allnutt-bioinformatics** [comment]
The script seems to read $node.label fine but at some point they all get to be NaN..

**Comment by theo-allnutt-bioinformatics** [comment]
ahh I see - all the genetrees need bootstrap too?? I guess that should have been obvious.

**Comment by mongiardino** [comment]
Only the gene trees need bootstraps.. you can pass a species tree with bootstraps but those won't be used

**Comment by theo-allnutt-bioinformatics** [comment]
Yes. Working now. Thanks.
