### ISSUE TITLE
'else' statement missing?

### ISSUE THREAD

**Issue by Ulises-Rosas** [mongiardino/genesortR#8]
https://github.com/mongiardino/genesortR/blob/48f84af1c1d627763edc9b6af5598d7f28befae6/genesortR.R#L484C3-L484C31

Hi,

Cool way to obtain the direction of the ordering!

I'm not fully sure, but I think there is a missing else statement around the line I referenced.

Saludos
Ulises

**Comment by mongiardino** [comment]
Hi Ulises, thanks for this! It does seem like you are correct, I will check and edit accordingly.

**Comment by mongiardino** [comment]
Edited as suggested, thanks again!
